---
bases:
  - ../../base
  - ../../base/migration

resources:
  - ./secrets.yaml
  - ./mocksaml-secrets.yaml
  - ./mocksaml-deployment.yaml

patches:
  - ./jackson-deployment.yaml
  - ./migratepg-job.yaml

images:
  - name: boxyhq/jackson
    newTag: 1.14.2
  - name: boxyhq/mock-saml
    newTag: 1.2.0
